[package]
name = "halo2-exp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2-base = "0.4.1"

[dev-dependencies]
rand = "0.8.4"
num-bigint = "0.4.4"
num-traits = "0.2.18"

